---
- hosts: "{{remote}}"
  # pre_tasks:
  #   - service: name=monit state=stopped
  #     become: yes
  #     ignore_errors: true
  become: yes
  roles:
    - openjdk
    - zookeeper-upgrade
  # post_tasks:
  #   - service: name=monit state=started
  #     become: yes
  #     ignore_errors: true
